# Set the reference directory relative to the script
set origin_dir [file dirname [info script]]/..
ipx::create_abstraction_definition work user regbus_rtl 1.0
ipx::create_bus_definition work user regbus 1.0
set_property xml_file_name $origin_dir/gen/ip/regbus_rtl.xml [ipx::current_busabs]
set_property xml_file_name $origin_dir/gen/ip/regbus.xml [ipx::current_busdef]
set_property bus_type_vlnv work:user:testing:1.0 [ipx::current_busabs]
ipx::save_abstraction_definition [ipx::current_busabs]
ipx::save_bus_definition [ipx::current_busdef]
update_ip_catalog

ipx::add_bus_abstraction_port RB_RADDR [ipx::current_busabs]
set_property master_presence required [ipx::get_bus_abstraction_ports RB_RADDR -of_objects [ipx::current_busabs]]
set_property master_width 16 [ipx::get_bus_abstraction_ports RB_RADDR -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_RADDR -of_objects [ipx::current_busabs]]
set_property slave_direction in [ipx::get_bus_abstraction_ports RB_RADDR -of_objects [ipx::current_busabs]]
set_property slave_width 16 [ipx::get_bus_abstraction_ports RB_RADDR -of_objects [ipx::current_busabs]]
set_property is_address true [ipx::get_bus_abstraction_ports RB_RADDR -of_objects [ipx::current_busabs]]
ipx::add_bus_abstraction_port RB_RDATA [ipx::current_busabs]
set_property master_presence required [ipx::get_bus_abstraction_ports RB_RDATA -of_objects [ipx::current_busabs]]
set_property master_direction in [ipx::get_bus_abstraction_ports RB_RDATA -of_objects [ipx::current_busabs]]
set_property master_width 32 [ipx::get_bus_abstraction_ports RB_RDATA -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_RDATA -of_objects [ipx::current_busabs]]
set_property slave_width 32 [ipx::get_bus_abstraction_ports RB_RDATA -of_objects [ipx::current_busabs]]
set_property is_data true [ipx::get_bus_abstraction_ports RB_RDATA -of_objects [ipx::current_busabs]]
ipx::add_bus_abstraction_port RB_RUPDATE [ipx::current_busabs]
set_property master_presence required [ipx::get_bus_abstraction_ports RB_RUPDATE -of_objects [ipx::current_busabs]]
set_property master_width 1 [ipx::get_bus_abstraction_ports RB_RUPDATE -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_RUPDATE -of_objects [ipx::current_busabs]]
set_property slave_direction in [ipx::get_bus_abstraction_ports RB_RUPDATE -of_objects [ipx::current_busabs]]
set_property slave_width 1 [ipx::get_bus_abstraction_ports RB_RUPDATE -of_objects [ipx::current_busabs]]
set_property is_data true [ipx::get_bus_abstraction_ports RB_RUPDATE -of_objects [ipx::current_busabs]]
ipx::add_bus_abstraction_port RB_RACK [ipx::current_busabs]
set_property master_direction in [ipx::get_bus_abstraction_ports RB_RACK -of_objects [ipx::current_busabs]]
set_property master_width 1 [ipx::get_bus_abstraction_ports RB_RACK -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_RACK -of_objects [ipx::current_busabs]]
set_property slave_width 1 [ipx::get_bus_abstraction_ports RB_RACK -of_objects [ipx::current_busabs]]
set_property is_data true [ipx::get_bus_abstraction_ports RB_RACK -of_objects [ipx::current_busabs]]

ipx::add_bus_abstraction_port RB_WADDR [ipx::current_busabs]
set_property master_presence required [ipx::get_bus_abstraction_ports RB_WADDR -of_objects [ipx::current_busabs]]
set_property master_width 16 [ipx::get_bus_abstraction_ports RB_WADDR -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_WADDR -of_objects [ipx::current_busabs]]
set_property slave_direction in [ipx::get_bus_abstraction_ports RB_WADDR -of_objects [ipx::current_busabs]]
set_property slave_width 16 [ipx::get_bus_abstraction_ports RB_WADDR -of_objects [ipx::current_busabs]]
set_property is_address true [ipx::get_bus_abstraction_ports RB_WADDR -of_objects [ipx::current_busabs]]
ipx::add_bus_abstraction_port RB_WDATA [ipx::current_busabs]
set_property master_presence required [ipx::get_bus_abstraction_ports RB_WDATA -of_objects [ipx::current_busabs]]
set_property master_width 32 [ipx::get_bus_abstraction_ports RB_WDATA -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_WDATA -of_objects [ipx::current_busabs]]
set_property slave_direction in [ipx::get_bus_abstraction_ports RB_WDATA -of_objects [ipx::current_busabs]]
set_property slave_width 32 [ipx::get_bus_abstraction_ports RB_WDATA -of_objects [ipx::current_busabs]]
set_property is_data true [ipx::get_bus_abstraction_ports RB_WDATA -of_objects [ipx::current_busabs]]
ipx::add_bus_abstraction_port RB_WUPDATE [ipx::current_busabs]
set_property master_presence required [ipx::get_bus_abstraction_ports RB_WUPDATE -of_objects [ipx::current_busabs]]
set_property master_width 1 [ipx::get_bus_abstraction_ports RB_WUPDATE -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_WUPDATE -of_objects [ipx::current_busabs]]
set_property slave_direction in [ipx::get_bus_abstraction_ports RB_WUPDATE -of_objects [ipx::current_busabs]]
set_property slave_width 1 [ipx::get_bus_abstraction_ports RB_WUPDATE -of_objects [ipx::current_busabs]]
set_property is_data true [ipx::get_bus_abstraction_ports RB_WUPDATE -of_objects [ipx::current_busabs]]
ipx::add_bus_abstraction_port RB_WACK [ipx::current_busabs]
set_property master_direction in [ipx::get_bus_abstraction_ports RB_WACK -of_objects [ipx::current_busabs]]
set_property master_width 1 [ipx::get_bus_abstraction_ports RB_WACK -of_objects [ipx::current_busabs]]
set_property slave_presence required [ipx::get_bus_abstraction_ports RB_WACK -of_objects [ipx::current_busabs]]
set_property slave_width 1 [ipx::get_bus_abstraction_ports RB_WACK -of_objects [ipx::current_busabs]]
set_property is_data true [ipx::get_bus_abstraction_ports RB_WACK -of_objects [ipx::current_busabs]]

ipx::save_bus_definition [ipx::current_busdef]

set_property bus_type_vlnv work:user:regbus:1.0 [ipx::current_busabs]
ipx::save_abstraction_definition [ipx::current_busabs]
update_ip_catalog -rebuild
