library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;
library work;
use work.common.all;
use work.atc_pkg.all;

entity atc_unit is
  port (
    -- clock and active-high reset
    ACLK                  : in std_logic; -- fast clock
    RST_I                 : in std_logic;
    -- UART clock generated by SoC:
    UCLK_I                : in std_logic; -- slow clock

    -- REGBUS interface
    S_REGBUS_RB_RADDR	  : in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
    S_REGBUS_RB_RDATA	  : out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
    S_REGBUS_RB_RUPDATE   : in  std_logic;
    S_REGBUS_RB_RACK      : out std_logic;

    S_REGBUS_RB_WUPDATE   : in  std_logic;
    S_REGBUS_RB_WADDR	  : in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
    S_REGBUS_RB_WDATA	  : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
    S_REGBUS_RB_WACK      : out std_logic;

    -- front panel LEMO inputs:
    LEMO_A_I              : in std_logic;
    LEMO_B_I              : in std_logic;

    TIMESTAMP_O           : out std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0);
    UCLK_O                : out std_logic;
    G_O                   : out std_logic_vector(C_NUM_TILE-1 downto 0);
    H_O                   : out std_logic_vector(C_NUM_TILE-1 downto 0)
    );
end atc_unit;

architecture behaviour of atc_unit is

  component rst_sync is
    port (
      CLK_I  : in   std_logic;
      RST_A  : in   std_logic;
      RST_O  : out  std_logic
    );
  end component;

  component atc_registers is
    port (
      CLK_I : in std_logic;
      RST_I : in std_logic;
      S_REGBUS_RB_RUPDATE : in  std_logic;
      S_REGBUS_RB_RADDR	  : in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
      S_REGBUS_RB_RDATA	  : out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      S_REGBUS_RB_RACK    : out std_logic;
      S_REGBUS_RB_WUPDATE : in  std_logic;
      S_REGBUS_RB_WADDR	  : in  std_logic_vector(C_RB_ADDR_WIDTH-1 downto 0);
      S_REGBUS_RB_WDATA	  : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      S_REGBUS_RB_WACK    : out std_logic;
      CONFIG_REQ_O        : out std_logic;
      COUNT_REQ_O         : out std_logic;
      COUNT_CMD_O         : out std_logic_vector(C_BYTE_WIDTH-1 downto 0);
      POKE_C_O            : out std_logic;
      MASK_C_O            : out std_logic_vector(C_NUM_TILE-1 downto 0);
      POKE_D_O            : out std_logic;
      MASK_D_O            : out std_logic_vector(C_NUM_TILE-1 downto 0);
      CONFIG_O            : out atc_config_t;
      STATUS_I            : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      COUNT_I             : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      TIMESTAMP_I         : in  std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0)
    );
  end component;

  component atc_bridge is
    port (
      CLK_A_I       : in  std_logic;
      RST_A_I       : in  std_logic;
      CONFIG_REQ_I  : in  std_logic;
      CONFIG_I      : in  atc_config_t;
      POKE_C_I      : in  std_logic;  -- CDC
      MASK_C_I      : in  std_logic_vector(C_NUM_TILE-1 downto 0);
      POKE_D_I      : in  std_logic;  -- CDC
      MASK_D_I      : in  std_logic_vector(C_NUM_TILE-1 downto 0);
      COUNT_REQ_I   : in  std_logic;
      COUNT_CMD_I   : in  std_logic_vector(C_BYTE_WIDTH-1 downto 0);
      COUNT_O       : out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      STATUS_O      : out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      TIMESTAMP_O   : out std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0);

      CLK_B_I       : in  std_logic;
      RST_B_I       : in  std_logic;
      CONFIG_O      : out atc_config_t;
      POKE_C_O      : out std_logic;
      MASK_C_O      : out std_logic_vector(C_NUM_TILE-1 downto 0);
      POKE_D_O      : out std_logic;
      MASK_D_O      : out std_logic_vector(C_NUM_TILE-1 downto 0);
      COUNT_REQ_O   : out std_logic;
      COUNT_CMD_O   : out std_logic_vector(C_BYTE_WIDTH-1 downto 0);
      COUNT_I       : in  std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      TIMESTAMP_TOGGLE_I : in std_logic;
      TIMESTAMP_TSYNC_I  : in std_logic
      );
  end component;

  component rising_edge_sync is
    generic ( DEBOUNCE_CYCLES : integer);
    port (
      CLK_I  : in  std_logic;
      RST_I  : in  std_logic;

      ASYNC_SIGNAL_I : in std_logic;
      POLARITY_I     : in std_logic;
      UPDATE_O       : out std_logic
      );
  end component;


  component atc_mux is
    port (
      CLK_I          : in  std_logic;
      RST_I          : in  std_logic;
      LEMO_A_I       : in  std_logic;
      LEMO_B_I       : in  std_logic;
      POKE_C_I       : in  std_logic;
      MASK_C_I       : in  std_logic_vector(C_NUM_TILE-1 downto 0);
      POKE_D_I       : in  std_logic;
      MASK_D_I       : in  std_logic_vector(C_NUM_TILE-1 downto 0);
      LOGIC_E_I      : in  std_logic;
      LOGIC_F_I      : in  std_logic;
      DST_LEMO_A_I   : in std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      DST_LEMO_B_I   : in std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      DST_POKE_C_I   : in std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      DST_POKE_D_I   : in std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      DST_LOGIC_E_I  : in std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      DST_LOGIC_F_I  : in std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
      G_O            : out std_logic_vector(9 downto 0) := (others => '0');
      H_O            : out std_logic_vector(9 downto 0) := (others => '0');
      T_O            : out std_logic
      );
  end component;

  component atc_counter is
    port (
      CLK_I	               : in  std_logic;
      RST_I	               : in  std_logic;
      LEMO_A_I	            : in  std_logic;
      LEMO_B_I	            : in  std_logic;
      POKE_C_I	            : in  std_logic;
      POKE_D_I	            : in  std_logic;
      G_I                   : in std_logic_vector(C_NUM_TILE -1  downto 0) ;
      H_I                   : in std_logic_vector(C_NUM_TILE -1 downto 0) ;
      UPDATE_I              : in  std_logic;
      COMMAND_I             : in  std_logic_vector(7 downto 0);
      COUNT_O               : out std_logic_vector(C_RB_DATA_WIDTH-1 downto 0)
    );
  end component;

  component timestamp_simple is
    port (
      CLK_I	        : in  std_logic;
      RST_I	        : in  std_logic;
      TIMESTAMP_O         : out std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0);
      TOGGLE_O            : out std_logic;
      TSYNC_O             : out std_logic
    );
  end component;

  component nchan_inverter is
    port (
      CLK_I      : in  std_logic;
      RST_I      : in  std_logic;
      SIG_I      : in  std_logic_vector(C_NUM_TILE-1 downto 0);
      POLARITY_I : in  std_logic_vector(C_NUM_TILE-1 downto 0);
      SIG_O      : out std_logic_vector(C_NUM_TILE-1 downto 0)
      );
  end component;

  -- system clock domain:
  signal sys_clk        : std_logic;
  signal sys_rst        : std_logic;

  signal sys_cfg_req    : std_logic;
  signal sys_cnt_req    : std_logic;
  signal sys_cnt_cmd    : std_logic_vector(C_BYTE_WIDTH-1 downto 0);
  signal sys_poke_c     : std_logic;
  signal sys_mask_c     : std_logic_vector(C_NUM_TILE-1 downto 0);
  signal sys_poke_d     : std_logic;
  signal sys_mask_d     : std_logic_vector(C_NUM_TILE-1 downto 0);

  signal sys_status     : std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
  signal sys_cfg        : atc_config_t;
  signal sys_cnt        : std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);
  signal sys_timestamp  : std_logic_vector(C_TIMESTAMP_WIDTH-1 downto 0);

  -- detector clock domain:
  signal det_clk        : std_logic;
  signal det_rst        : std_logic;

  signal det_lemo_a     : std_logic;
  signal det_lemo_b     : std_logic;

  signal det_cfg_req    : std_logic;
  signal det_cnt_req    : std_logic;
  signal det_cnt_cmd    : std_logic_vector(C_BYTE_WIDTH-1 downto 0);
  signal det_poke_c     : std_logic;
  signal det_mask_c     : std_logic_vector(C_NUM_TILE-1 downto 0);
  signal det_poke_d     : std_logic;
  signal det_mask_d     : std_logic_vector(C_NUM_TILE-1 downto 0);

  signal det_cfg        : atc_config_t;
  signal det_cnt        : std_logic_vector(C_RB_DATA_WIDTH-1 downto 0);

  signal det_rst_or     : std_logic;
  signal det_toggle     : std_logic;
  signal det_tsync      : std_logic;

  signal det_g          : std_logic_vector(9 downto 0) := (others => '0');
  signal det_h          : std_logic_vector(9 downto 0) := (others => '0');
  signal det_t         : std_logic;

begin
  sys_clk <= ACLK;
  sys_rst <= RST_I;
  det_clk <= UCLK_I;
  UCLK_O  <= UCLK_I;

  TIMESTAMP_O <= sys_timestamp;

  dut0: rst_sync
    port map (
      CLK_I  => det_clk,
      RST_A  => sys_rst,
      RST_O  => det_rst
    );

  atcreg0: atc_registers port map (
    CLK_I               => sys_clk,
    RST_I               => sys_rst,
    S_REGBUS_RB_RUPDATE => S_REGBUS_RB_RUPDATE,
    S_REGBUS_RB_RADDR   => S_REGBUS_RB_RADDR,
    S_REGBUS_RB_RDATA   => S_REGBUS_RB_RDATA,
    S_REGBUS_RB_RACK    => S_REGBUS_RB_RACK,
    S_REGBUS_RB_WUPDATE => S_REGBUS_RB_WUPDATE,
    S_REGBUS_RB_WADDR   => S_REGBUS_RB_WADDR,
    S_REGBUS_RB_WDATA   => S_REGBUS_RB_WDATA,
    S_REGBUS_RB_WACK    => S_REGBUS_RB_WACK,
    CONFIG_REQ_O        => sys_cfg_req,
    CONFIG_O            => sys_cfg,
    COUNT_REQ_O         => sys_cnt_req,
    COUNT_CMD_O         => sys_cnt_cmd,
    POKE_C_O            => sys_poke_c,
    MASK_C_O            => sys_mask_c,
    POKE_D_O            => sys_poke_d,
    MASK_D_O            => sys_mask_d,
    STATUS_I            => sys_status,
    COUNT_I             => sys_cnt,
    TIMESTAMP_I         => sys_timestamp
  );

  atcbridge0: atc_bridge port map (
    CLK_A_I          => sys_clk,
    RST_A_I          => sys_rst,
    CONFIG_REQ_I     => sys_cfg_req,
    CONFIG_I         => sys_cfg,
    POKE_C_I         => sys_poke_c,
    MASK_C_I         => sys_mask_c,
    POKE_D_I         => sys_poke_d,
    MASK_D_I         => sys_mask_d,
    COUNT_REQ_I      => sys_cnt_req,
    COUNT_CMD_I      => sys_cnt_cmd,
    COUNT_O          => sys_cnt,
    STATUS_O         => sys_status,
    TIMESTAMP_O      => sys_timestamp,
    CLK_B_I          => det_clk,
    RST_B_I          => det_rst,
    CONFIG_O         => det_cfg,
    POKE_C_O         => det_poke_c,
    MASK_C_O         => det_mask_c,
    POKE_D_O         => det_poke_d,
    MASK_D_O         => det_mask_d,
    COUNT_REQ_O      => det_cnt_req,
    COUNT_CMD_O      => det_cnt_cmd,
    COUNT_I          => det_cnt,
    TIMESTAMP_TOGGLE_I => det_toggle,
    TIMESTAMP_TSYNC_I  => det_tsync
  );

 lemoa0: rising_edge_sync
   generic map(
     DEBOUNCE_CYCLES => 4
     )

   port map (
     CLK_I  => det_clk,
     RST_I  => det_rst,
     ASYNC_SIGNAL_I => LEMO_A_I,
     POLARITY_I => det_cfg.polarity(0),
     UPDATE_O => det_lemo_a
   );

  lemob0: rising_edge_sync
    generic map(
      DEBOUNCE_CYCLES => 4
     )
   port map (
     CLK_I  => det_clk,
     RST_I  => det_rst,
     ASYNC_SIGNAL_I => LEMO_B_I,
     POLARITY_I => det_cfg.polarity(1),
     UPDATE_O => det_lemo_b
   );

  atcmux0: atc_mux port map (
    CLK_I         => det_clk,
    RST_I         => det_rst,
    LEMO_A_I      => det_lemo_a,
    LEMO_B_I      => det_lemo_b,
    POKE_C_I      => det_poke_c,
    MASK_C_I      => det_mask_c,
    POKE_D_I      => det_poke_d,
    MASK_D_I      => det_mask_d,
    LOGIC_E_I     => '0' ,
    LOGIC_F_I     => '0' ,
    DST_LEMO_A_I  => det_cfg.dst_lemo_a,
    DST_LEMO_B_I  => det_cfg.dst_lemo_b,
    DST_POKE_C_I  => det_cfg.dst_poke_c,
    DST_POKE_D_I  => det_cfg.dst_poke_d,
    DST_LOGIC_E_I => det_cfg.dst_logic_e,
    DST_LOGIC_F_I => det_cfg.dst_logic_f,
    G_O           => det_g,
    H_O           => det_h,
    T_O           => det_t
  );

  atccnt0: atc_counter port map (
    CLK_I	     => det_clk,
    RST_I 	     => det_rst,
    LEMO_A_I	     => det_lemo_a,
    LEMO_B_I	     => det_lemo_b,
    POKE_C_I	     => det_poke_c,
    POKE_D_I	     => det_poke_d,
    G_I              => det_g,
    H_I              => det_h,
    UPDATE_I         => det_cnt_req,
    COMMAND_I        => det_cnt_cmd,
    COUNT_O          => det_cnt
  );

  -- we reset timestamp for a global reset or from a configurable timing pulse from the MUX:
  det_rst_or <= det_rst or det_t;
  tstamp0: timestamp_simple port map (
    CLK_I              => det_clk,
    RST_I              => det_rst_or,
    --TIMESTAMP_O        => det_timestamp,  -- not yet used...
    TOGGLE_O           => det_toggle,
    TSYNC_O            => det_tsync
    );

  ginv0: nchan_inverter port map (
    CLK_I	=> det_clk,
    RST_I 	=> det_rst,
    SIG_I	=> det_g,
    POLARITY_I  => det_cfg.polarity(13 downto 4),
    SIG_O	=> G_O
  );

  hinv0: nchan_inverter port map (
    CLK_I	=> det_clk,
    RST_I 	=> det_rst,
    SIG_I	=> det_h,
    POLARITY_I  => det_cfg.polarity(25 downto 16),
    SIG_O	=> H_O
  );


end behaviour;
